# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import service_pb2 as proto_dot_service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """UserService defines our user management service functionality
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/service.UserService/GetUser',
                request_serializer=proto_dot_service__pb2.GetUserRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/service.UserService/CreateUser',
                request_serializer=proto_dot_service__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.User.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/service.UserService/ListUsers',
                request_serializer=proto_dot_service__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListUsersResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """UserService defines our user management service functionality
    """

    def GetUser(self, request, context):
        """GetUser retrieves a user by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """CreateUser creates a new user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """ListUsers retrieves all users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=proto_dot_service__pb2.GetUserRequest.FromString,
                    response_serializer=proto_dot_service__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_service__pb2.CreateUserRequest.FromString,
                    response_serializer=proto_dot_service__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=proto_dot_service__pb2.ListUsersRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('service.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """UserService defines our user management service functionality
    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.UserService/GetUser',
            proto_dot_service__pb2.GetUserRequest.SerializeToString,
            proto_dot_service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.UserService/CreateUser',
            proto_dot_service__pb2.CreateUserRequest.SerializeToString,
            proto_dot_service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.UserService/ListUsers',
            proto_dot_service__pb2.ListUsersRequest.SerializeToString,
            proto_dot_service__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProductServiceStub(object):
    """ProductService defines our product management functionality
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/service.ProductService/GetProduct',
                request_serializer=proto_dot_service__pb2.GetProductRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Product.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/service.ProductService/CreateProduct',
                request_serializer=proto_dot_service__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.Product.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/service.ProductService/ListProducts',
                request_serializer=proto_dot_service__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.ListProductsResponse.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """ProductService defines our product management functionality
    """

    def GetProduct(self, request, context):
        """GetProduct retrieves a product by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """CreateProduct creates a new product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """ListProducts retrieves all products
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=proto_dot_service__pb2.GetProductRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Product.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=proto_dot_service__pb2.CreateProductRequest.FromString,
                    response_serializer=proto_dot_service__pb2.Product.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=proto_dot_service__pb2.ListProductsRequest.FromString,
                    response_serializer=proto_dot_service__pb2.ListProductsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('service.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """ProductService defines our product management functionality
    """

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.ProductService/GetProduct',
            proto_dot_service__pb2.GetProductRequest.SerializeToString,
            proto_dot_service__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.ProductService/CreateProduct',
            proto_dot_service__pb2.CreateProductRequest.SerializeToString,
            proto_dot_service__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.ProductService/ListProducts',
            proto_dot_service__pb2.ListProductsRequest.SerializeToString,
            proto_dot_service__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
