# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\x07service\"<\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"3\n\x10ListUsersRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"1\n\x11ListUsersResponse\x12\x1c\n\x05users\x18\x01 \x03(\x0b\x32\r.service.User\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"H\n\x14\x43reateProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"6\n\x13ListProductsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\":\n\x14ListProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.service.Product2\xc3\x01\n\x0bUserService\x12\x33\n\x07GetUser\x12\x17.service.GetUserRequest\x1a\r.service.User\"\x00\x12\x39\n\nCreateUser\x12\x1a.service.CreateUserRequest\x1a\r.service.User\"\x00\x12\x44\n\tListUsers\x12\x19.service.ListUsersRequest\x1a\x1a.service.ListUsersResponse\"\x00\x32\xe1\x01\n\x0eProductService\x12<\n\nGetProduct\x12\x1a.service.GetProductRequest\x1a\x10.service.Product\"\x00\x12\x42\n\rCreateProduct\x12\x1d.service.CreateProductRequest\x1a\x10.service.Product\"\x00\x12M\n\x0cListProducts\x12\x1c.service.ListProductsRequest\x1a\x1d.service.ListProductsResponse\"\x00\x42 Z\x1egithub.com/gnad103/go-ex/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/gnad103/go-ex/proto'
  _globals['_USER']._serialized_start=32
  _globals['_USER']._serialized_end=92
  _globals['_GETUSERREQUEST']._serialized_start=94
  _globals['_GETUSERREQUEST']._serialized_end=122
  _globals['_CREATEUSERREQUEST']._serialized_start=124
  _globals['_CREATEUSERREQUEST']._serialized_end=185
  _globals['_LISTUSERSREQUEST']._serialized_start=187
  _globals['_LISTUSERSREQUEST']._serialized_end=238
  _globals['_LISTUSERSRESPONSE']._serialized_start=240
  _globals['_LISTUSERSRESPONSE']._serialized_end=289
  _globals['_PRODUCT']._serialized_start=291
  _globals['_PRODUCT']._serialized_end=362
  _globals['_GETPRODUCTREQUEST']._serialized_start=364
  _globals['_GETPRODUCTREQUEST']._serialized_end=395
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=397
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=469
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=471
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=525
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=527
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=585
  _globals['_USERSERVICE']._serialized_start=588
  _globals['_USERSERVICE']._serialized_end=783
  _globals['_PRODUCTSERVICE']._serialized_start=786
  _globals['_PRODUCTSERVICE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
